@include('layouts.admin.header')
@include('layouts.admin.navbar')
@include('layouts.admin.sidebar')
@include('layouts.admin.body')
@include('layouts.admin.footer_text')
@include('layouts.admin.footer')